using System.ComponentModel.DataAnnotations;

namespace MyApp.WebMVC.Models
{
    public class RegisterUserViewModel
    {
        // GUID will be generated by the system, not user input
        public Guid Id { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 6, ErrorMessage = "Password must be at least 6 characters long.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Compare("Password", ErrorMessage = "Passwords do not match.")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
    }
}
